[project]
name = "misp-warninglists"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

[dependency-groups]
test = [
    "check-jsonschema>=0.38.0",
]
all = [
    "beautifulsoup4>=4.15.0",
    "dnspython>=2.8.0",
    "pyasn1>=0.6.4",
    "pyasn1-modules>=0.4.2",
    "pyopenssl<23.0.0",
    "python-dateutil==2.8.1",
    "requests>=2.34.2",
    {include-group = "test"}
]
