# This workflow is managed by gh actions-lock.

name: Update Lists

on:
  schedule:
    - cron: '0 2 * * 1' # At 02:00 on Monday
  workflow_dispatch: {}  

permissions: {}

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production
# deployments to complete.
concurrency:
  group: auto-update
  cancel-in-progress: false

jobs:
  build:
    name: Update Lists
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      updated-lists-artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - uses: step-security/harden-runner@v2.20.1
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          cache: pip
          python-version-file: pyproject.toml
      - name: Restore List Cache
        uses: actions/cache@v6.1.0
        with:
          key: lists-downloads-${{ github.run_id }}
          restore-keys: lists-downloads-
          path: ${{ github.workspace }}/tmp/
      - name: Install Dependencies
        run: |-
          sudo apt update
          sudo apt install -y moreutils
          pip install -r pylock.toml --no-deps
      - name: Update Lists
        env:
          CLOUDFLARE_DOMAINS_MUST_GENERATE: true
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_RADAR_API_TOKEN }}
        run: |-
          set -eux
          set -o pipefail
          ./generate_all.sh
          if [ "$(git status --porcelain | grep -c '')" -le 0 ]; then
            echo 'No updates to publish. Exiting early.'
            exit 1
          fi
          tar -czf ../repo-snapshot.tar.gz -C "$GITHUB_WORKSPACE" .
          mv ../repo-snapshot.tar.gz "$GITHUB_WORKSPACE"
      - name: Upload Changes
        id: upload-artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: auto-updated-lists
          path: ${{ github.workspace }}/repo-snapshot.tar.gz
          overwrite: true
          retention-days: 1
  create-attestations:
    name: Create Attestations
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
    steps:
      - uses: step-security/harden-runner@v2.20.1
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Download Artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          artifact-ids: ${{ needs.build.outputs.updated-lists-artifact-id }}
      - name: Decompress Artiacts
        run: |-
          set -eux
          set -o pipefail
          tar -xzf repo-snapshot.tar.gz -C "$GITHUB_WORKSPACE"
      - name: Create Attestations
        uses: actions/attest@v4.2.2
        with:
          subject-path: lists/*/list.json
    
  publish-pr:
    name: Commit Changes and Publish PR
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@v2.20.1
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Download Changes
        uses: actions/download-artifact@v8.0.1
        with:
          artifact-ids: ${{ needs.build.outputs.updated-lists-artifact-id }}
      - name: Create Commit and  PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_REF: ${{ github.base_ref || github.ref }}
          HEAD_BRANCH_PREFIX: ci/update-lists-
          PR_AUTHOR: app/github-actions
        run: |-
          set -eux
          set -o pipefail

          BASE_BRANCH="$(printf '%s' "$BASE_REF" | awk -F/ '{printf $3}')"
          HEAD_BRANCH="$HEAD_BRANCH_PREFIX$BASE_BRANCH"

          # Prepare Downloaded Artifact
          tar -xzf repo-snapshot.tar.gz -C "$GITHUB_WORKSPACE"
          rm repo-snapshot.tar.gz

          # Setup Git
          gh auth setup-git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # Create Commit
          COMMIT_MSG="chg: [lists] updated $(date '+%Y-%m-%d')"
          git add --all
          git commit -m "$COMMIT_MSG"
          git fetch
          git push -u origin --force-with-lease @:"$HEAD_BRANCH"

          # Create PR
          PR_TITLE="[$BASE_BRANCH] $COMMIT-MSG"
          # Check for existing PRs
          EXISTING_OPEN_PR="$(gh pr list \
            -R "$GITHUB_REPOSITORY" \
            -A "$PR_AUTHOR" \
            --json=baseRefName,headRepositoryOwner,headRepository,headRefName,number \
            -q '.[] | (
              .baseRefName + " "
              + .headRepositoryOwner.login + "/"
              + .headRepository.name + " "
              + .headRefName + " "
              + (.number | tostring))' \
            | grep "^$BASE_BRANCH $GITHUB_REPOSITORY $HEAD_BRANCH" \
            | head -n1)" || true

          # Modify existing, open PR (if any)
          if [ "$(printf '%s\n' "$EXISTING_OPEN_PR" | grep -c '')" -gt 0 ]; then
            echo 'Existing PR found. Updating it...'
            EXISTING_OPEN_PR_NUMBER="$(printf '%s' "$EXISTING_OPEN_PR" | awk '{printf $3}')"
            gh pr edit "$EXISTING_OPEN_PR_NUMBER" \
              -t "$PR_TITLE" \
              -b 'Auto-update of lists.'

          # Create new PR if there's no existing, open PR.
          else
            echo 'No existing PR found. Creating new PR...'
            gh pr create \
              -B "$BASE_BRANCH" \
              -H "$HEAD_BRANCH" \
              -t "$PR_TITLE" \
              -b 'Auto-update of lists.'
          fi
